### ISSUE TITLE
Pronouns role

### ISSUE THREAD

**Issue by shuting-hu** [nwplus/nwPlus_discord_bot#123]
- [x] Add pronoun role selector

Optional:
- [ ] Customize additional pronoun roles
- [ ] Choice to have it in nickname instead of as role

**Comment by JPGarCar** [comment]
@mwang2000 you already working on this?

**Comment by shuting-hu** [comment]
@JPGarCar yeet the required feature is done in the pronouns branch, optional points are low priority for now
