### ISSUE TITLE
Automated self-care reminders

### ISSUE THREAD

**Issue by shuting-hu** [nwplus/nwPlus_discord_bot#124]
- [ ] Set interval for message to send every hour in self-care channel
- [ ] Preferably grabbing messages from Firebase (so whenever that's fixed?)

**Comment by shuting-hu** [comment]
@JPGarCar sorry I should've been more clear! the messages will be sent to a self-care channel so the general implementation will be similar to the discord contest feature but simplified because it acts more like an announcement. It's probably going to be opt-in or users can just mute/adjust channel notifications.

**Comment by JPGarCar** [comment]
Okay cool! Just a fyi, if you mention a role on those messages, it won't matter if they have the server or channel muted, they will still be notified. If you are only sending a message with no role mentions, then they will most probably not get a notification. I think it would be a great idea to be opt-in and we could even send it via DM just to not have one extra channel. Thoughts @mwang2000 ?
