### ISSUE TITLE
cmd-f Learn access channel view

### ISSUE THREAD

**Issue by shuting-hu** [nwplus/nwPlus_discord_bot#125]
Verification command for learn day access on cmd-f server

**Comment by JPGarCar** [comment]
So just to be clear @shuting-hu , we want two verifications, one for learn and one for cmd-f, they will each give a different role yes?

**Comment by shuting-hu** [comment]
@JPGarCar correct, for cmd-f we can just stick with !verify and if it's easier for you guys we can just use !attend for learn. We want to tailor these roles to different channel accesses on the server.

**Comment by JPGarCar** [comment]
Sounds good! I will look at some implementations. I was thinking changing verify to be !verify <type> email

So we could do:
- !verify learn email@gmail.com
- !verify cmd-f email@gmail.com

And the admins can add different verifications, each will give a different role, it would just be hard on the back end, how will the program know what to use to check if they should be verified?

Might just have to hard code it for now?

@shuting-hu We are using firebase for verification data yes? So hacker emails will be on firebase? Do we have the schema for that or are we getting that via excel file?

**Comment by shuting-hu** [comment]
@JPGarCar OMG so sorry I missed this comment! ya that sounds good too, will the shift to DM verifications be ready for cmd-f or are we sticking to the channel? emails will be available via excel/csv (gform registration similar to HC).
