### ISSUE TITLE
Add multiple prompt to Prompt class

### ISSUE THREAD

**Issue by JPGarCar** [nwplus/nwPlus_discord_bot#139]
Would be nice to have promots for multiple roles, channels, mentions.
- [x] roles
- [x] channels
- [x] mentions

Furthermore, would be nice to have a yes/no prompt plus any other prompt after, all in one call.
- [ ] Yes/No + Prompt call

**Comment by mwang2000** [comment]
I'm iffy on the last checkbox with the yes/no + another prompt call one because that would mean the function returns a bunch of different data types
